sudo: required

services:
  - docker

language: node_js

node_js: '6'

cache: yarn

before_install:
  # Startup test db
  #
  - docker run -d -p "62223:9200" --name rumors-test-db elasticsearch
  - sleep 10 # wait for elasticsearch

script:
  - npm run lint
  - npm run test -- --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

after_script:
  - docker stop rumors-test-db
  - docker rm rumors-test-db
